CREATE DATABASE QLHM

CREATE TABLE LOGINN(
	USENAME NVARCHAR(100) PRIMARY KEY,
	PASS NVARCHAR(8),
	QUYEN nvarchar(10) )

CREATE TABLE NGUOIHM(
	NAME_ID NVARCHAR(100) PRIMARY KEY,
	HOTEN NVARCHAR(100),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	DIACHI NVARCHAR(100),
	CANNANG FLOAT,
	MAU_ID NVARCHAR(100),
	RESULT_MAUID NVARCHAR(100),
	HANHTRINH_ID NVARCHAR(100))

CREATE TABLE DONVIMAU(
	MAU_ID NVARCHAR(100) PRIMARY KEY,
	THETICH nvarchar(10),
	ngayhm DATE,
	DIADIEMHM NVARCHAR(100),
	abo nchar(5),
	rh nchar(5))

CREATE TABLE KETQUA(
	RESULT_MAUID NVARCHAR(100) PRIMARY KEY,
	KHANGTHEBATTHUONG NVARCHAR(100),
	HBSAG NVARCHAR(100),
	ANTIHCV NVARCHAR(100),
	HIVAG_AB NVARCHAR(100),
	GIANGMAI NVARCHAR(100),
	MAU_ID NVARCHAR(100))

CREATE TABLE HANHTRINHDVM(
	HANHTRINH_ID NVARCHAR(100) PRIMARY KEY,
	DIADIEMLUUTRU NVARCHAR(100),
	THOIGIANLUUTRU DATE,
	DIADIEMSD NVARCHAR(100),
	THOIGIANSD DATE,
	MAU_ID NVARCHAR(100))